name: Test PR

on:
  pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSG
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: mkdir dist/
    - run: npm run build.server
